# -*- coding: utf-8 -*-
"""area of circle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145lekpQRAqtNqQbMv0_XcdGepyzWR9PL
"""



radius=float(input("enter the radius"))
pi=3.14
area=pi*radius**2
print("area of circle is 1",area)