# -*- coding: utf-8 -*-
"""sum of two numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TIISrUaf9UhGbP5YU6yfla3fxyMubsJ0
"""



a=int(input("enter 1st number:"))
b=int(input("enter 2nd number:"))
sum=a+b
print(sum)



a=float(input("enter 1st number:"))
b=float(input("enter 2nd number:"))
sum=a*b
print(sum)